# Generated by Django 2.2 on 2020-08-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('status', models.CharField(choices=[('L', 'Libre'), ('P', 'Prestado'), ('R', 'En Reparacion')], default='LI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('numLibros', models.IntegerField()),
                ('adeudo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Persona')),
                ('matricula', models.IntegerField()),
            ],
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Persona')),
                ('numEmpleado', models.IntegerField()),
            ],
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Material')),
            ],
            bases=('core.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fechaSalida', models.DateField()),
                ('fechaRegreso', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Material')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Material')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Editorial')),
            ],
            bases=('core.material',),
        ),
    ]
